# Generated by Django 4.0.2 on 2022-05-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место ловли')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('photo', models.FileField(blank=True, default='media/karp.jpg', null=True, upload_to='')),
            ],
        ),
    ]
