# Generated by Django 4.0.4 on 2022-05-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_excelfile_delete_trophy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
